apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saiyedin786/shopNow.git'
    targetRevision: HEAD
    path: kubernetes/argocd/apps
  destination:
    server: 'https://33225B69BEC8D20BA1F7D08577E03A88.gr7.ap-south-1.eks.amazonaws.com'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
