apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saiyedin786/Hero-capstone-project.git'
    targetRevision: HEAD
    path: kubernetes/argocd/apps
  destination:
    server: 'https://F4D8E85478EED3B8B2F32FACA4A6A8E7.gr7.ap-south-1.eks.amazonaws.com'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
