apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/saiyedin786/Hero-capstone-project.git'
    targetRevision: HEAD
    path: kubernetes/helm/charts/admin
    helm:
      valueFiles: []
      releaseName: admin
  destination:
    server: 'https://E7A7A4713A01052C7BC01F7A8EB2CB0E.gr7.ap-south-1.eks.amazonaws.com'
    namespace: shopnow-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
